### ISSUE TITLE
Fehler beim Bestätigen einer Notification mit Kommentar

### ISSUE THREAD

**Issue by sstolz84** [TeraIT-at/icinga-telegram-bot#1]
Wenn ich versuche eine Notification mit Kommentar zu bestätigen bekomme ich im Telegram Client einen Fehler nach Eingabe des Kommentars und auf der Console ebenfalls (nicht als Dienst gestartet).

Installation erfolgte wie in der Anleitung beschrieben! :)

![Fehler_Console](https://user-images.githubusercontent.com/4427510/77911943-fb4a5b00-7291-11ea-86da-b1c7d63d7e39.PNG)
![Screenshot_20200330-141638-01](https://user-images.githubusercontent.com/4427510/77911965-056c5980-7292-11ea-8ae4-ec551af9d302.jpeg)

**Comment by joni1993** [comment]
Hi, danke für den Report.
Der Bot benötigt deine Antwort als "Reply" auf seine Nachricht damit er weiß welcher Host/Service gemeint ist. 
Versuche es mal als Reply statt einfach so zu antworten.


Natürlich ist die Fehlermeldung trotzdem ein Problem... da lass ich mir was einfallen.

**Comment by joni1993** [comment]
Kannst du es mal den neuesten Commit (https://github.com/joni1993/icinga-telegram-bot/commit/23cc79986a8608caff4081ab115dfc5dac48c704) testen?

**Comment by sstolz84** [comment]
Du hast recht, mit Reply funktioniert es.
Ich habe den neuesten Commit ausprobiert, der funktioniert.
Aber: die Bestätigung des Acknowledgement dauert ca. 20 Sekunden und auf der Console gibt es folgende Meldung (danach funktioniert es aber, wie es soll):

`2020-03-30 17:33:55,470 - telegram.ext.updater - ERROR - Error while getting Updates: Internal server error: restart (500)
2020-03-30 17:33:56,517 - telegram.ext.updater - INFO - Flood control exceeded. Retry in 5 seconds
`

**Comment by sstolz84** [comment]
Kurz noch zur Erklärung, warum ich direkt geantwortet hab:

Wenn eine Notification ankommen gibt es unten die 2 Buttons (Acknowledge, Acknowledge (with Comment), ich hab auf den mit Kommentar getippt und danach sollte ich den Text eingeben. Das wird dann wohl als einfache Antwort gewertet...

**Comment by joni1993** [comment]
> 
> 
> Du hast recht, mit Reply funktioniert es.
> Ich habe den neuesten Commit ausprobiert, der funktioniert.
> Aber: die Bestätigung des Acknowledgement dauert ca. 20 Sekunden und auf der Console gibt es folgende Meldung (danach funktioniert es aber, wie es soll):
> 
> `2020-03-30 17:33:55,470 - telegram.ext.updater - ERROR - Error while getting Updates: Internal server error: restart (500) 2020-03-30 17:33:56,517 - telegram.ext.updater - INFO - Flood control exceeded. Retry in 5 seconds `

Da dürftest du einfach an ein Request Limit der Telegram API stoßen, da werd ich wohl nicht viel dran ändern können, sofern es keine Probleme beim Bot selbst verursacht.

**Comment by sstolz84** [comment]
Alles klar, nochmal vielen Dank für deine tolle Arbeit und den schnellen Fix!

**Comment by joni1993** [comment]
Gerne!
